# Plant puns for 9 AM Slack message. Add/remove as you like.
import random

PLANT_PUNS = [
    "Rise and shine—it's time to get your photosynthesis on!",
    "Good morning! Let's get to the root of today's plant.",
    "Time to branch out! Here's your plant of the day.",
    "Don't leaf without checking out today's plant!",
    "Stem into the day with today's featured plant.",
    "Bloom where you're planted—starting with this one!",
    "Seeds like a good morning? Here's your plant of the day.",
    "Let's turn over a new leaf together.",
    "Thyme to wake up! Your plant of the day is here.",
    "No need to be thorny—today's plant is a friendly one.",
    "Fern-tastic morning! Check out today's plant.",
    "A little growth mindset: here's your plant of the day.",
    "Petal to the metal—today's plant won't disappoint.",
    "Moss-t definitely worth a look: your plant of the day.",
    "Ready to grow your knowledge? Here's today's plant.",
    "Leaf it to us—we've got your plant of the day.",
    "Rooting for you this morning! Here's today's plant.",
    "What's the buzz? It's plant-of-the-day o'clock!",
    "Sprout of bed? Here's something to brighten your morning.",
    "Stalk about a great way to start the day!",
    "Your daily dose of green: plant of the day.",
    "Let's get botanical! Today's plant is waiting.",
    "No need to garden-variety morning—here's something special.",
    "Kale yeah! It's plant-of-the-day time.",
    "Chlorophyll and happy! Your plant of the day is here.",
    "Dig in—today's plant is a good one.",
    "A vine way to start the day!",
    "Shrub not—today's plant is worth a look.",
    "Aloe there! Your plant of the day has arrived.",
    "Lettuce celebrate—it's plant-of-the-day time!",
    "Be-leaf it or not, here's your plant of the day.",
    "Unbe-leaf-able morning content: today's plant.",
    "Herb you go—your plant of the day.",
    "Clover and out: today's plant is here.",
    "Fig-ure you'd want to see today's plant!",
    "Pumpkin spice and everything nice—plus this plant.",
    "Yarrow ready? Here's your plant of the day.",
    "Dew tell—today's plant is a beauty.",
    "I'm so glad we're on the same plant page. Here's today's pick!",
    "Cactus do it—check out today's plant!",
    "Sage advice: start the day with this plant.",
    "Berry nice to see you! Here's today's plant.",
    "Pine for something green? Look no further.",
    "Orchid you not—today's plant is lovely.",
    "A-peel-ing way to start the day: plant of the day.",
    "Lichen this a lot! Your plant of the day.",
    "Garden variety morning? Nope—today's pick is special.",
    "Reed between the lines: today's plant is great.",
    "Bamboo-zle your brain with today's plant.",
    "Nectar day than never—here's your plant of the day.",
    "What's the dill? Your plant of the day is here!",
    "Rose to the occasion—check out today's plant.",
    "Don't be sappy—unless it's about this plant!",
    "I'm rooting for you! And here's your plant of the day.",
    "Foliage-t about your troubles—here's today's plant.",
    "It's vine o'clock somewhere! (It's plant-of-the-day time.)",
    "Succulent morning! Your plant of the day awaits.",
    "Let's get to the stem of things—today's plant.",
    "No need to be soilless—we've got your plant of the day.",
    "Budding with excitement? Here's today's plant!",
    "You're going to love this one—it's un-fir-gettable.",
    "A little compost-ment goes a long way. Here's your plant!",
    "Treelicious morning! Check out today's plant.",
    "Don't worry, bee happy—and meet today's plant.",
    "This one's a real gem. (Get it? Gem? Okay, here's the plant.)",
    "Shallot we take a look at today's plant?",
    "Parsley the thought—but here's your plant of the day!",
    "Turnip the volume on your plant knowledge!",
    "Bean there, done that? Not with this plant!",
    "Peas be with you—and with your plant of the day.",
    "You're doing vine! Here's today's plant.",
    "Asparagus to meet you—and to introduce today's plant!",
    "Celery-brate good times—and this plant!",
    "Romaine calm and check out today's plant.",
    "We're not mushroom for puns—okay, one more: here's your plant!",
    "Basil-y the best way to start the day.",
    "Olive you and I love this plant!",
    "It's a date—with today's plant of the day.",
    "Chive got a good feeling about today's plant.",
    "We've bean waiting to show you this one!",
    "Poppy morning! Here's your plant of the day.",
    "We're not pulling your leg(ume)—today's plant is here!",
    "Rue the day? No—celebrate the plant of the day!",
    "Heather we like it or not, here's today's plant!",
    "Ivy got something special for you: today's plant.",
    "Jasmine and relax—and enjoy today's plant.",
    "Marigold morning! Check out today's plant.",
    "We're not tulip-ing you—this plant is great.",
    "Hyacinth you're going to love today's plant!",
    "Daffodil-ly-dally no more—here's your plant!",
    "Iris you could see today's plant. (You can! Right here.)",
    "Lavender your expectations—today's plant delivers.",
    "Pansy for the interruption—here's your plant of the day!",
    "Zinnia minute—you're going to want to see this plant.",
    "Aster if you've seen today's plant yet!",
    "Daisy to say we've got a great plant for you.",
    "Sunflower power! Here's your plant of the day.",
    "Pistil stop—here's your plant of the day!",
]


def pick_pun():
    return random.choice(PLANT_PUNS)
